spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

services:
  order-service:
    image: order-service:latest
    deploy:
      replicas: 3
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
